CREATE TABLE IF NOT EXISTS public.perfis_telegram (
  user_id UUID NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  chat_id BIGINT NOT NULL UNIQUE,
  data_vinculo TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.gastos_telegram (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  mensagem_bruta TEXT NOT NULL,
  descricao TEXT,
  valor NUMERIC CHECK (valor IS NULL OR valor > 0),
  categoria TEXT,
  data_vencimento DATE,
  data_criacao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  id_grupo_parcela TEXT,
  parcela_atual INTEGER CHECK (parcela_atual IS NULL OR parcela_atual > 0),
  total_parcelas INTEGER CHECK (total_parcelas IS NULL OR total_parcelas > 0),
  origem TEXT NOT NULL DEFAULT 'telegram_message'
);

CREATE TABLE IF NOT EXISTS public.statement_imports (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  source TEXT NOT NULL CHECK (source IN ('card_pdf', 'telegram_pdf')),
  file_name TEXT NOT NULL,
  transactions_count INTEGER NOT NULL DEFAULT 0 CHECK (transactions_count >= 0),
  total_amount NUMERIC NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.gastos_telegram
  ADD COLUMN IF NOT EXISTS categoria TEXT,
  ADD COLUMN IF NOT EXISTS origem TEXT NOT NULL DEFAULT 'telegram_message';

ALTER TABLE public.perfis_telegram ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gastos_telegram ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.statement_imports ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.transactions
  ALTER COLUMN date TYPE DATE USING date::date,
  ADD CONSTRAINT transactions_amount_positive CHECK (amount > 0);

ALTER TABLE public.fixed_expenses
  ADD CONSTRAINT fixed_expenses_amount_positive CHECK (amount > 0),
  ADD CONSTRAINT fixed_expenses_due_day_valid CHECK (due_day BETWEEN 1 AND 31);

ALTER TABLE public.gastos_telegram
  ADD CONSTRAINT gastos_telegram_valor_positive CHECK (valor IS NULL OR valor > 0),
  ADD CONSTRAINT gastos_telegram_parcela_atual_positive CHECK (parcela_atual IS NULL OR parcela_atual > 0),
  ADD CONSTRAINT gastos_telegram_total_parcelas_positive CHECK (total_parcelas IS NULL OR total_parcelas > 0);

ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_phone_len CHECK (char_length(phone) <= 32),
  ADD CONSTRAINT profiles_full_name_len CHECK (char_length(full_name) <= 120);

ALTER TABLE public.transactions
  ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'manual',
  ADD COLUMN IF NOT EXISTS import_id UUID REFERENCES public.statement_imports(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb;

DROP POLICY IF EXISTS "Allow authenticated users to view gastos_telegram" ON public.gastos_telegram;
DROP POLICY IF EXISTS "Users can view own gastos_telegram" ON public.gastos_telegram;
DROP POLICY IF EXISTS "Users can insert own gastos_telegram" ON public.gastos_telegram;
DROP POLICY IF EXISTS "Users can update own gastos_telegram" ON public.gastos_telegram;
DROP POLICY IF EXISTS "Users can delete own gastos_telegram" ON public.gastos_telegram;

CREATE POLICY "Users can view own gastos_telegram"
  ON public.gastos_telegram FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own gastos_telegram"
  ON public.gastos_telegram FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own gastos_telegram"
  ON public.gastos_telegram FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own gastos_telegram"
  ON public.gastos_telegram FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view own statement imports" ON public.statement_imports;
DROP POLICY IF EXISTS "Users can insert own statement imports" ON public.statement_imports;
DROP POLICY IF EXISTS "Users can delete own statement imports" ON public.statement_imports;

CREATE POLICY "Users can view own statement imports"
  ON public.statement_imports FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own statement imports"
  ON public.statement_imports FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own statement imports"
  ON public.statement_imports FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile"
  ON public.profiles FOR UPDATE
  TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own preferences" ON public.user_preferences;
CREATE POLICY "Users can update own preferences"
  ON public.user_preferences FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own transactions" ON public.transactions;
CREATE POLICY "Users can update own transactions"
  ON public.transactions FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own fixed expenses" ON public.fixed_expenses;
CREATE POLICY "Users can update own fixed expenses"
  ON public.fixed_expenses FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own telegram profile" ON public.perfis_telegram;
CREATE POLICY "Users can update own telegram profile"
  ON public.perfis_telegram FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, phone)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data ->> 'full_name', ''),
    COALESCE(NEW.raw_user_meta_data ->> 'phone', '')
  )
  ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    full_name = EXCLUDED.full_name,
    phone = EXCLUDED.phone;
  RETURN NEW;
END;
$$;
