
ALTER TABLE public.profiles ADD COLUMN full_name text NOT NULL DEFAULT '';
ALTER TABLE public.profiles ADD COLUMN phone text NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS public.gastos_telegram (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  mensagem_bruta TEXT NOT NULL,
  descricao TEXT,
  valor NUMERIC,
  data_vencimento DATE,
  data_criacao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  id_grupo_parcela TEXT,
  parcela_atual INTEGER,
  total_parcelas INTEGER
);

ALTER TABLE public.gastos_telegram ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow authenticated users to view gastos_telegram" ON public.gastos_telegram;
DROP POLICY IF EXISTS "Users can view own gastos_telegram" ON public.gastos_telegram;

CREATE POLICY "Users can view own gastos_telegram"
ON public.gastos_telegram
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);
